[project]
name = "internal-knowledge-assistance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<=3.12"
dependencies = [
    "chromadb>=1.5.1",
    "fastapi>=0.133.1",
    "langchain>=1.2.10",
    "langchain-ollama>=1.0.1",
    "pre-commit>=4.5.1",
    "prometheus-client>=0.24.1",
    "pydantic-settings>=2.13.1",
    "tiktoken>=0.12.0",
    "uvicorn>=0.41.0",
]
